/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'customer' : Principal,
  'scheduledTime' : Time,
  'createdTime' : Time,
  'address' : string,
  'notes' : string,
  'serviceId' : bigint,
  'price' : bigint,
  'worker' : [] | [Principal],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface Service {
  'id' : bigint,
  'serviceType' : ServiceType,
  'name' : string,
  'description' : string,
  'basePrice' : bigint,
}
export interface ServiceInput {
  'serviceType' : ServiceType,
  'name' : string,
  'description' : string,
  'basePrice' : bigint,
}
export type ServiceType = { 'cleaning' : null } |
  { 'generalHelp' : null } |
  { 'cooking' : null } |
  { 'dishwashing' : null } |
  { 'ironing' : null } |
  { 'laundry' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'earnings' : bigint,
  'jobCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'worker' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptBooking' : ActorMethod<[bigint], undefined>,
  'addService' : ActorMethod<[ServiceInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<[bigint, Time, string, string], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getPendingBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'initializePresetServices' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCustomer' : ActorMethod<[string], undefined>,
  'registerWorker' : ActorMethod<[string], undefined>,
  'removeService' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateService' : ActorMethod<[bigint, ServiceInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];