/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'cleaning' : IDL.Null,
  'generalHelp' : IDL.Null,
  'cooking' : IDL.Null,
  'dishwashing' : IDL.Null,
  'ironing' : IDL.Null,
  'laundry' : IDL.Null,
});
export const ServiceInput = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'customer' : IDL.Principal,
  'scheduledTime' : Time,
  'createdTime' : Time,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'serviceId' : IDL.Nat,
  'price' : IDL.Nat,
  'worker' : IDL.Opt(IDL.Principal),
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'worker' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'earnings' : IDL.Nat,
  'jobCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptBooking' : IDL.Func([IDL.Nat], [], []),
  'addService' : IDL.Func([ServiceInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, Time, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getPendingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'initializePresetServices' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCustomer' : IDL.Func([IDL.Text], [], []),
  'registerWorker' : IDL.Func([IDL.Text], [], []),
  'removeService' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateService' : IDL.Func([IDL.Nat, ServiceInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'cleaning' : IDL.Null,
    'generalHelp' : IDL.Null,
    'cooking' : IDL.Null,
    'dishwashing' : IDL.Null,
    'ironing' : IDL.Null,
    'laundry' : IDL.Null,
  });
  const ServiceInput = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'customer' : IDL.Principal,
    'scheduledTime' : Time,
    'createdTime' : Time,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'serviceId' : IDL.Nat,
    'price' : IDL.Nat,
    'worker' : IDL.Opt(IDL.Principal),
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'worker' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'earnings' : IDL.Nat,
    'jobCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptBooking' : IDL.Func([IDL.Nat], [], []),
    'addService' : IDL.Func([ServiceInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, Time, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getPendingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'initializePresetServices' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCustomer' : IDL.Func([IDL.Text], [], []),
    'registerWorker' : IDL.Func([IDL.Text], [], []),
    'removeService' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateService' : IDL.Func([IDL.Nat, ServiceInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };